### PR TITLE
Add Swift workflow

### PR DESCRIPTION
**Pull request by SplittyDev**
Create GitHub action workflow for building and testing SchafKit on macOS.

## Issues
~Currently these tests are failing because the Swift distribution used in the workflow doesn't recognize new features of SwiftUI, which cause it to break. I'm looking into whether this can be fixed.~

After updating the workflow, we're getting another error.
The issue is being tracked at: https://github.com/fwal/setup-swift/issues/133

Generally, another issue is that this only tests the macOS-specific code.
Not sure if there's any way to actually test the iOS-specific code in an automated fashion.

### CODE REVIEW

**Comment by SplittyDev** [comment]
@JannThomas please check the build error.

Screen Shot 2020-10-06 at 20 11 40

Is this a valid error?

**Comment by JannThomas** [comment]
There was a valid error in the iOS target (fixed with 63bf898). But for the macOS target afaics

**Comment by JannThomas** [comment]
The target SDK version seems to be 10.15.6. That is wrong. It should be 10.16 or 11.0, depending upon which is available. Can you do that? Doesn't make sense still that it does not compile, as it is marked with `@available(macOS 10.16, *)`.

**Comment by SplittyDev** [comment]
> The target SDK version seems to be 10.15.6. That is wrong. It should be 10.16 or 11.0, depending upon which is available. Can you do that?

I'm actually pretty sure that it's not possible to compile with 11.0 at the moment.
Screen Shot 2020-10-06 at 22 42 05

So I guess we'll either have to somehow make this work with macOS 10.15 or wait for release.

> Doesn't make sense still that it does not compile, as the line in question is marked with `@available(macOS 10.16, *)`

With your annotation that should work though..

**Comment by JannThomas** [comment]
I guess we'll just have to wait 🤷🏻‍♂️

**Pull request merged**
